### ISSUE TITLE
Get lfs out of quota

### ISSUE THREAD

**Issue by jascase901** [pubgeo/dfc2019#10]
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                                                                                          
error: failed to fetch some objects from 'https://github.com/pubgeo/dfc2019.git/info/lfs'

**Comment by slipperysaxophone** [comment]
This only affects the acquisition of the pre-trained models via git.

You can optionally train the model yourself. I'll look into putting the model files on the torrent server (and will update this post when I do).

**Comment by pubgeo** [comment]
Have neglected to close out old issues. Doing so now. If there's still an issue, please resubmit. Thanks.
