### ISSUE TITLE
about track4 pointnet2 training data

### ISSUE THREAD

**Issue by yoyo91** [pubgeo/dfc2019#11]
Hello,
I retrained pointnet2 with provided codes on 99 point clouds which are produced by create_train_dataset.py and tested on 11 validation point clouds which are produced by create_train_dataset.py. But it is 6% lower than provided trained model. Does the baseline use a different split?

Thank you very much!

**Comment by pubgeo** [comment]
Have neglected to close out old issues. Doing so now. If there's still an issue, please resubmit. Thanks.
