### ISSUE TITLE
Unrectified images and corrected RPC for Track2

### ISSUE THREAD

**Issue by sonalipatil** [pubgeo/dfc2019#12]
Where can I get access to unrectified images and corrected RPC or affine camera models?

The following is mentioned on page4 of the publication "Metadata such as RPC, epipolar rectifying homographies, and collection dates are retained for each stereo pair"  I am not able to find RPC parameters in METADATA.json files or any of the .tif files.

**Comment by pubgeo** [comment]
I'm not sure if this got a response. I think some questions were answered by email, and my notifications were turned off for some reason. Let me know if you still have an issue and we'll work through it.
