### ISSUE TITLE
Is it possibile to submit predictions to the leaderboard of the DFC2019 challenge?

### ISSUE THREAD

**Issue by lauraset** [pubgeo/dfc2019#14]
Hi, @pubgeo, I want to submit predictions to the leaderboard of the DFC2019 challenge, but it said "Your request to participate in this challenge has been received and a decision is pending." in the website https://competitions.codalab.org/competitions/20212#participate. Do you know how long it will take? Or whether the leaderboard has already closed?

**Comment by pubgeo** [comment]
GRSS owns the CodaLab contest repo. As far as I know, the leaderboard should stay open. May just take a bit for someone to respond to the email notification. If nobody responds in a couple days, please let us know and we'll reach out.

**Comment by lauraset** [comment]
OK, thank you for your help.
