### ISSUE TITLE
From where can I download the whole datasets please?

### ISSUE THREAD

**Issue by Bobholamovic** [pubgeo/dfc2019#2]
Hello there, it's been several days since the release of the training and validation dataset. Yet I couldn't pull these data to the local till now, though I had registered on the official website to make the links visible, all as guided. For the first few days, the links contained in the `BT` files seemed invalid, as the resources couldn't be connected. And today found the links to the `BT` files and the net disks on the official page all gone. 

As is the case, could you please show me another way to download the dataset? Sorry for any possible trouble on reading caused by languages issues as my English is not so good.

**Comment by liuxuvip** [comment]
Data is the king.

**Comment by pubgeo** [comment]
The [data/README.md](https://github.com/pubgeo/dfc2019/tree/master/data) explains how to get all the data. 
Namely you must first register for the competition. From there you will receive information about the box account as well as torrents.

**Comment by deangelo** [comment]
Unfortunately, the page linked in the email received after registration email does not (anymore?) include the download links. The "Get the data" paragaph does not contain any link:

Is there yet another page with the links?

------------------------------
...
Get the data

 Data for the various tracks of the 2019 Data Fusion Contest are very large: more than 300 GB. Therefore we had to split the dataset to allow for a la carte data selection. Data archives are split according to tracks and modalities. For tracks 1 to 3, very high resolution RGB images are distributed with the reference data for training, while the corresponding multispectral images come in another package. We also propose various file sharing modalities for each bunch of data.

 Baselines

 Baseline solutions are provided for each challenge track to help participants get started quickly and 
...
-------------------------

**Comment by Bobholamovic** [comment]
@deangelo yea dude we were talking about exactly the same thing, and now I guess another way is to search and find the data on the `box drive` .

**Comment by pubgeo** [comment]
Sorry for the inconvenience. The link in the IADF email after registration should be the one you use. I'm checking on this today, and we'll provide an update. Thanks for your patience.

**Comment by pubgeo** [comment]
This issue has been resolved by the registration team.

**Comment by Bobholamovic** [comment]
@pubgeo Thanks for the links. However, I ran into yet another two problems:
> 1. The downloading process will (every time and by no accident) be interrupted and stop early with no prompt or warnings when I try to fetch a large (roughly `>1GB`) file.
> 2. The torrent file always throws an error like `resource could not be connected` and the downloading couldn't even start.

 Since I'm in China, I think these might have something to do with the Great Firewall. Could you make a mirror of the archives on a cloud drive (such as `Baiduyun`) accessible for the participants in China?

**Comment by lauraset** [comment]
@Bobholamovic Hello, have you successfully obtained the data ? could you share it for Chinese users?
Thanks a lot.

**Comment by Bobholamovic** [comment]
@lauraset 
Well I'd like to, but it's been more than a year since I got those data downloaded onto my computer and now they are not there any more. I've noticed that you come from WHU? There should be someone around you who participated in the competition, and have kept the dataset on there harddrive. As the dataset is quite em, big, copying can be much faster than downloading. Perhaps you should find them and ask for a copy.

**Comment by pubgeo** [comment]
A copy of the data is also here: https://ieee-dataport.org/open-access/data-fusion-contest-2019-dfc2019

**Comment by lauraset** [comment]
Hi @Bobholamovic and @pubgeo , Thank you for your help. I successfully download the dataset from the website https://ieee-dataport.org/open-access/data-fusion-contest-2019-dfc2019
