### ISSUE TITLE
ValueError('all input arrays must have the same shape') in create_train_dataset.py

### ISSUE THREAD

**Issue by pournami123** [pubgeo/dfc2019#8]
I am trying to run pointnet2 on my own data set, which has got a '_PC3.txt' file with xyzRGB values and a corresponding '_CLS.txt' file. I am getting a error like this when I ran create_train_dataset.py
![image](https://user-images.githubusercontent.com/33048649/61350352-eef9ab80-a884-11e9-8928-c0a82a4fc176.png)
But i checked the shape of CLS and PC3 file, both are same. Is it a problem because of multi-threading? If so how can I rectify it?
I tried in the LiNUX environment as well. But it gave the same error.
Please help

**Comment by pubgeo** [comment]
Have neglected to close out old issues. Doing so now. If there's still an issue, please resubmit. Thanks.
