### ISSUE TITLE
Including RGB in the .las 

### ISSUE THREAD

**Issue by pournami123** [pubgeo/dfc2019#9]
@pubgeo I am using this version of Pointnet++, my dataset has yxzRGB values in it. But when i tried to feed in the RGB values to the .las using the laspy somehow it is not happening. 
Can you help please

**Comment by slipperysaxophone** [comment]
This sounds like an issue with laspy. Could you narrow down the dfc specific issue if applicable?

**Comment by pubgeo** [comment]
Have neglected to close out old issues. Doing so now. If there's still an issue, please resubmit. Thanks.
